DROP TABLE IF EXISTS `PropertyLevel`;
CREATE TABLE `PropertyLevel` (
       `PropertyLevelID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
       `Name` TEXT NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
