DROP TABLE IF EXISTS `RequirementType`;
CREATE TABLE `RequirementType` (
       `RequirementTypeID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
       `Name` TEXT NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
