
CREATE TABLE Page
(
PageID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY DEFAULT NULL,
Page VARCHAR(255) NOT NULL DEFAULT '',
Active INT(11) NOT NULL DEFAULT -1,
Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
