DROP TABLE IF EXISTS `PokemonBossCompleted`;
CREATE TABLE `PokemonBossCompleted` (
  `PokemonBossCompletedID` int(11) NOT NULL AUTO_INCREMENT,
  `PokemonBossID` int(11) DEFAULT NULL,
  `PokemonID` int(11) DEFAULT NULL,
  `PokemonFormID` int(11) DEFAULT NULL,
  `CombatPower` int(11) DEFAULT NULL,
  `UserID` int(11) DEFAULT NULL,
  `PokemonRaidPassID` int(11) DEFAULT NULL,
  `Shiny` int(11) NOT NULL DEFAULT 0,
  `Shadow` int(11) NOT NULL DEFAULT 0,
  `Caught` int(11) NOT NULL DEFAULT 0,
  `Active` int(11) NOT NULL DEFAULT -1,
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `CreatedBy` int(11) NOT NULL DEFAULT 1,
  `Deleted` int(11) NOT NULL DEFAULT 0,
  `DeletedAt` datetime DEFAULT NULL,
  `DeletedBy` int(11) DEFAULT NULL,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PokemonBossCompletedID`),
  KEY `Shiny` (`Shiny`),
  KEY `Shadow` (`Shadow`),
  KEY `CombatPower` (`CombatPower`),
  KEY `Caught` (`Caught`),
  CONSTRAINT `PokemonBossCompleted_ibfk` FOREIGN KEY (`PokemonRaidPassID`) REFERENCES `PokemonRaidPass` (`PokemonRaidPassID`),
  CONSTRAINT `PokemonBossCompleted_ibfk_1` FOREIGN KEY (`PokemonBossID`) REFERENCES `PokemonBoss` (`PokemonBossID`),
  CONSTRAINT `PokemonBossCompleted_ibfk_2` FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE SET NULL,
  CONSTRAINT `PokemonBossCompleted_ibfk_4` FOREIGN KEY (`PokemonFormID`) REFERENCES `PokemonForm` (`PokemonFormID`),
  CONSTRAINT `PokemonBossCompleted_ibfk_5` FOREIGN KEY (`PokemonID`) REFERENCES `Pokemon` (`PokemonID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
