DROP TABLE IF EXISTS `Pokemon`;
CREATE TABLE `Pokemon` (
  `PokemonID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT '',
  `Description` VARCHAR(255) DEFAULT '',
  `BaseAttack` int(11) DEFAULT 0,
  `BaseStamina` int(11) DEFAULT 0,
  `BaseDefense` int(11) DEFAULT 0,
  `PokemonRarityID` INT(11) DEFAULT NULL,
  `PokemonTypeID1` INT(11) DEFAULT NULL,
  `PokemonTypeID2` INT(11) DEFAULT NULL,
  `PokemonGenerationID` INT(11) DEFAULT NULL,
  `Released` INT(11) NOT NULL DEFAULT 0,
  `Shiny` INT(11) NOT NULL DEFAULT 0,
  `Shadow` INT(11) NOT NULL DEFAULT 0,
  `Ditto` INT(11) NOT NULL DEFAULT 0,
  `Alolan` INT(11) NOT NULL DEFAULT 0,
  `Galar` INT(11) NOT NULL DEFAULT 0,  
  `Active` INT(11) NOT NULL DEFAULT -1,
  `CreatedAt` timestamp NOT NULL DEFAULT current_timestamp(),
  `CreatedBy` INT(11) NOT NULL DEFAULT 1,
  `Deleted` INT(11) NOT NULL DEFAULT 0,
  `DeletedAt` datetime DEFAULT NULL,
  `DeletedBy` INT(11) DEFAULT NULL,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PokemonID`),
  KEY `Name` (`Name`),
  KEY `Shiny` (`Shiny`),
  KEY `Shadow` (`Shadow`),
  KEY `Alolan` (`Alolan`),
  KEY `Galar` (`Galar`),
  CONSTRAINT `Pokemon_ibfk` FOREIGN KEY (`PokemonRarityID`) REFERENCES `PokemonRarity` (`PokemonRarityID`),
  CONSTRAINT `Pokemon_ibfk_1` FOREIGN KEY (`PokemonTypeID1`) REFERENCES `PokemonType` (`PokemonTypeID`),
  CONSTRAINT `Pokemon_ibfk_2` FOREIGN KEY (`PokemonTypeID2`) REFERENCES `PokemonType` (`PokemonTypeID`),
  CONSTRAINT `Pokemon_ibfk_3` FOREIGN KEY (`PokemonGenerationID`) REFERENCES `PokemonGeneration` (`PokemonGenerationID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
